wip : Supprimer un utilisateur en tant qu'Admin
La logique du endpoint est en place cependant j'ai une erreur de types :

```shell
error CS1503: Argument 1: cannot convert from 'string' to 'WaitifyApi.Dtos.AdminDeleteUserRequest
```