wip : Endpoint live KPIs...
Erreur actuelle : `error CS1061: 'double' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'double' could be found (are you missing a using directive or an assembly reference?)`